services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./backend/build:/app/backend/public
      # - ./frontend/public:/app/frontend/public
      - ./conf/nginx:/etc/nginx
      - ./conf/letsencrypt:/etc/letsencrypt
        # - ./conf/nginx/sites-available/strapi.conf:/etc/nginx/sites-available/strapi.conf
        # - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        # - ./conf/nginx/certs:/etc/nginx/certs
      - ./logs/nginx/:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      # - frontend
      - strapi
    networks:
      - strapi

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - ./logs/frontend:/root/.npm/_logs
    networks:
      - strapi
    

  strapi:
    container_name: strapi
    build:
      context: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./backend/.env
    image: postgres:12.0-alpine
    # environment:
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #   POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      # - strapi-data:/var/lib/postgresql/data/ #using a volume
      - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
